#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage:"
  echo "  $ install-python <version> <prefix>"
  echo "  $ install-python 3.6.8 /path/to/install"
  exit 1
fi

export PYTHON_VERSION="$1"

# remove trailing slash in the "prefix" parameter
export PREFIX=`echo $2 | sed 's/^\(.*\)\/$/\1/g'`

cd /tmp
# remove previous installations
rm -rf Python-*

# download the specific .tar.gz file from the official site for the given version
wget "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz"

# extract
tar xzf Python-$PYTHON_VERSION.tgz
cd Python-$PYTHON_VERSION

# compile & install into the given "prefix" path
#./configure --prefix=$PREFIX/python$PYTHON_VERSION --enable-optimizations
./configure --prefix=$PREFIX/python$PYTHON_VERSION
make
make install
cd ..

# cleaning downloaded assets
rm -rf Python-$PYTHON_VERSION*

cd $PWD
exit
